/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mdsd.androidGenerator.AndroidGeneratorFactory
 * @model kind="package"
 * @generated
 */
public interface AndroidGeneratorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "androidGenerator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mdsd/AndroidGenerator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "androidGenerator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AndroidGeneratorPackage eINSTANCE = org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.AndroidAppProjectImpl <em>Android App Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidAppProjectImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getAndroidAppProject()
   * @generated
   */
  int ANDROID_APP_PROJECT = 0;

  /**
   * The feature id for the '<em><b>Applications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANDROID_APP_PROJECT__APPLICATIONS = 0;

  /**
   * The number of structural features of the '<em>Android App Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANDROID_APP_PROJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationImpl <em>Application</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplication()
   * @generated
   */
  int APPLICATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__ATTRIBUTES = 1;

  /**
   * The number of structural features of the '<em>Application</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationAttributeImpl <em>Application Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationAttributeImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationAttribute()
   * @generated
   */
  int APPLICATION_ATTRIBUTE = 2;

  /**
   * The number of structural features of the '<em>Application Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_ATTRIBUTE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationVersionImpl <em>Application Version</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationVersionImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationVersion()
   * @generated
   */
  int APPLICATION_VERSION = 3;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_VERSION__RESULT = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Targetsdk</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_VERSION__TARGETSDK = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Application Version</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_VERSION_FEATURE_COUNT = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TargetSDKImpl <em>Target SDK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.TargetSDKImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getTargetSDK()
   * @generated
   */
  int TARGET_SDK = 4;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_SDK__RESULT = 0;

  /**
   * The feature id for the '<em><b>Minsdk</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_SDK__MINSDK = 1;

  /**
   * The number of structural features of the '<em>Target SDK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_SDK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.MinSDKImpl <em>Min SDK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.MinSDKImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getMinSDK()
   * @generated
   */
  int MIN_SDK = 5;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SDK__RESULT = 0;

  /**
   * The number of structural features of the '<em>Min SDK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SDK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationPermissionListImpl <em>Application Permission List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationPermissionListImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationPermissionList()
   * @generated
   */
  int APPLICATION_PERMISSION_LIST = 6;

  /**
   * The feature id for the '<em><b>Permissions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_PERMISSION_LIST__PERMISSIONS = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Application Permission List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_PERMISSION_LIST_FEATURE_COUNT = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.PermissionImpl <em>Permission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.PermissionImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getPermission()
   * @generated
   */
  int PERMISSION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Permission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementListImpl <em>Application Element List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementListImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationElementList()
   * @generated
   */
  int APPLICATION_ELEMENT_LIST = 8;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_ELEMENT_LIST__ELEMENTS = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Application Element List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_ELEMENT_LIST_FEATURE_COUNT = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationMainActivityImpl <em>Application Main Activity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationMainActivityImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationMainActivity()
   * @generated
   */
  int APPLICATION_MAIN_ACTIVITY = 9;

  /**
   * The feature id for the '<em><b>Launcher Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_MAIN_ACTIVITY__LAUNCHER_ACTIVITY = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Application Main Activity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_MAIN_ACTIVITY_FEATURE_COUNT = APPLICATION_ATTRIBUTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementImpl <em>Application Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationElement()
   * @generated
   */
  int APPLICATION_ELEMENT = 10;

  /**
   * The feature id for the '<em><b>Activity Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_ELEMENT__ACTIVITY_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_ELEMENT__NAME = 1;

  /**
   * The number of structural features of the '<em>Application Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ModelImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getModel()
   * @generated
   */
  int MODEL = 11;

  /**
   * The feature id for the '<em><b>Activity Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ACTIVITY_TYPE = APPLICATION_ELEMENT__ACTIVITY_TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = APPLICATION_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Modellist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODELLIST = APPLICATION_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = APPLICATION_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ModelListImpl <em>Model List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ModelListImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getModelList()
   * @generated
   */
  int MODEL_LIST = 12;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST__TYPE = 0;

  /**
   * The feature id for the '<em><b>Getset</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST__GETSET = 1;

  /**
   * The number of structural features of the '<em>Model List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.GetSetImpl <em>Get Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.GetSetImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getGetSet()
   * @generated
   */
  int GET_SET = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_SET__NAME = 0;

  /**
   * The number of structural features of the '<em>Get Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_SET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.TypeImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getType()
   * @generated
   */
  int TYPE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.FragmentImpl <em>Fragment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.FragmentImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getFragment()
   * @generated
   */
  int FRAGMENT = 15;

  /**
   * The feature id for the '<em><b>Activity Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT__ACTIVITY_TYPE = APPLICATION_ELEMENT__ACTIVITY_TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT__NAME = APPLICATION_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Activity Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT__ACTIVITY_ATTRIBUTES = APPLICATION_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fragment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT_FEATURE_COUNT = APPLICATION_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityImpl <em>Activity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivity()
   * @generated
   */
  int ACTIVITY = 16;

  /**
   * The feature id for the '<em><b>Activity Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY__ACTIVITY_TYPE = APPLICATION_ELEMENT__ACTIVITY_TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY__NAME = APPLICATION_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Activity Type Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES = APPLICATION_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Activity Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY__ACTIVITY_ATTRIBUTES = APPLICATION_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Activity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_FEATURE_COUNT = APPLICATION_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeAttributesImpl <em>Activity Type Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeAttributesImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivityTypeAttributes()
   * @generated
   */
  int ACTIVITY_TYPE_ATTRIBUTES = 17;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_TYPE_ATTRIBUTES__FILTER = 0;

  /**
   * The number of structural features of the '<em>Activity Type Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_TYPE_ATTRIBUTES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeImpl <em>Activity Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivityType()
   * @generated
   */
  int ACTIVITY_TYPE = 18;

  /**
   * The number of structural features of the '<em>Activity Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityLayoutAttributesImpl <em>Activity Layout Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityLayoutAttributesImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivityLayoutAttributes()
   * @generated
   */
  int ACTIVITY_LAYOUT_ATTRIBUTES = 19;

  /**
   * The feature id for the '<em><b>Layout Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Activity Layout Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_LAYOUT_ATTRIBUTES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.LayoutElementImpl <em>Layout Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.LayoutElementImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getLayoutElement()
   * @generated
   */
  int LAYOUT_ELEMENT = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Layout Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TextViewImpl <em>Text View</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.TextViewImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getTextView()
   * @generated
   */
  int TEXT_VIEW = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_VIEW__NAME = LAYOUT_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Text View</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_VIEW_FEATURE_COUNT = LAYOUT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ButtonImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = LAYOUT_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = LAYOUT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.FilterQueryImpl <em>Filter Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.FilterQueryImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getFilterQuery()
   * @generated
   */
  int FILTER_QUERY = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_QUERY__NAME = 0;

  /**
   * The feature id for the '<em><b>Filter Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_QUERY__FILTER_ATTRIBUTES = 1;

  /**
   * The number of structural features of the '<em>Filter Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_QUERY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.FilterAttributesImpl <em>Filter Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.FilterAttributesImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getFilterAttributes()
   * @generated
   */
  int FILTER_ATTRIBUTES = 24;

  /**
   * The feature id for the '<em><b>Distance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_ATTRIBUTES__DISTANCE = 0;

  /**
   * The number of structural features of the '<em>Filter Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_ATTRIBUTES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.DistanceImpl <em>Distance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.DistanceImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getDistance()
   * @generated
   */
  int DISTANCE = 25;

  /**
   * The feature id for the '<em><b>Unit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE__UNIT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Results</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE__RESULTS = 2;

  /**
   * The number of structural features of the '<em>Distance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.NumberImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 26;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__VALUE = 0;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.OperatorImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 27;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.UnitImpl <em>Unit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.UnitImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getUnit()
   * @generated
   */
  int UNIT = 28;

  /**
   * The number of structural features of the '<em>Unit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TypeMapImpl <em>Type Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.TypeMapImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getTypeMap()
   * @generated
   */
  int TYPE_MAP = 29;

  /**
   * The number of structural features of the '<em>Type Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_MAP_FEATURE_COUNT = ACTIVITY_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.LessImpl <em>Less</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.LessImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getLess()
   * @generated
   */
  int LESS = 30;

  /**
   * The number of structural features of the '<em>Less</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.MoreImpl <em>More</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.MoreImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getMore()
   * @generated
   */
  int MORE = 31;

  /**
   * The number of structural features of the '<em>More</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MORE_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.EqualImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 32;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.MetersImpl <em>Meters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.MetersImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getMeters()
   * @generated
   */
  int METERS = 33;

  /**
   * The number of structural features of the '<em>Meters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METERS_FEATURE_COUNT = UNIT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ImperialImpl <em>Imperial</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mdsd.androidGenerator.impl.ImperialImpl
   * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getImperial()
   * @generated
   */
  int IMPERIAL = 34;

  /**
   * The number of structural features of the '<em>Imperial</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPERIAL_FEATURE_COUNT = UNIT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.AndroidAppProject <em>Android App Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Android App Project</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.AndroidAppProject
   * @generated
   */
  EClass getAndroidAppProject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.AndroidAppProject#getApplications <em>Applications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Applications</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.AndroidAppProject#getApplications()
   * @see #getAndroidAppProject()
   * @generated
   */
  EReference getAndroidAppProject_Applications();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Application <em>Application</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Application
   * @generated
   */
  EClass getApplication();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.Application#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Application#getName()
   * @see #getApplication()
   * @generated
   */
  EAttribute getApplication_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.Application#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Application#getAttributes()
   * @see #getApplication()
   * @generated
   */
  EReference getApplication_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ApplicationAttribute <em>Application Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Attribute</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationAttribute
   * @generated
   */
  EClass getApplicationAttribute();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ApplicationVersion <em>Application Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Version</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationVersion
   * @generated
   */
  EClass getApplicationVersion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.ApplicationVersion#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Result</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationVersion#getResult()
   * @see #getApplicationVersion()
   * @generated
   */
  EReference getApplicationVersion_Result();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.ApplicationVersion#getTargetsdk <em>Targetsdk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Targetsdk</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationVersion#getTargetsdk()
   * @see #getApplicationVersion()
   * @generated
   */
  EReference getApplicationVersion_Targetsdk();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.TargetSDK <em>Target SDK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target SDK</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.TargetSDK
   * @generated
   */
  EClass getTargetSDK();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.TargetSDK#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Result</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.TargetSDK#getResult()
   * @see #getTargetSDK()
   * @generated
   */
  EReference getTargetSDK_Result();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.TargetSDK#getMinsdk <em>Minsdk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Minsdk</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.TargetSDK#getMinsdk()
   * @see #getTargetSDK()
   * @generated
   */
  EReference getTargetSDK_Minsdk();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.MinSDK <em>Min SDK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Min SDK</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.MinSDK
   * @generated
   */
  EClass getMinSDK();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.MinSDK#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Result</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.MinSDK#getResult()
   * @see #getMinSDK()
   * @generated
   */
  EReference getMinSDK_Result();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ApplicationPermissionList <em>Application Permission List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Permission List</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationPermissionList
   * @generated
   */
  EClass getApplicationPermissionList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.ApplicationPermissionList#getPermissions <em>Permissions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Permissions</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationPermissionList#getPermissions()
   * @see #getApplicationPermissionList()
   * @generated
   */
  EReference getApplicationPermissionList_Permissions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Permission <em>Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permission</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Permission
   * @generated
   */
  EClass getPermission();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.Permission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Permission#getName()
   * @see #getPermission()
   * @generated
   */
  EAttribute getPermission_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ApplicationElementList <em>Application Element List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Element List</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationElementList
   * @generated
   */
  EClass getApplicationElementList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.ApplicationElementList#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationElementList#getElements()
   * @see #getApplicationElementList()
   * @generated
   */
  EReference getApplicationElementList_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ApplicationMainActivity <em>Application Main Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Main Activity</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationMainActivity
   * @generated
   */
  EClass getApplicationMainActivity();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mdsd.androidGenerator.ApplicationMainActivity#getLauncherActivity <em>Launcher Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Launcher Activity</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationMainActivity#getLauncherActivity()
   * @see #getApplicationMainActivity()
   * @generated
   */
  EReference getApplicationMainActivity_LauncherActivity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ApplicationElement <em>Application Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Element</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationElement
   * @generated
   */
  EClass getApplicationElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.ApplicationElement#getActivityType <em>Activity Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Activity Type</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationElement#getActivityType()
   * @see #getApplicationElement()
   * @generated
   */
  EReference getApplicationElement_ActivityType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.ApplicationElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ApplicationElement#getName()
   * @see #getApplicationElement()
   * @generated
   */
  EAttribute getApplicationElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.Model#getModellist <em>Modellist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modellist</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Model#getModellist()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Modellist();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ModelList <em>Model List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model List</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ModelList
   * @generated
   */
  EClass getModelList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.ModelList#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ModelList#getType()
   * @see #getModelList()
   * @generated
   */
  EReference getModelList_Type();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.ModelList#getGetset <em>Getset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Getset</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ModelList#getGetset()
   * @see #getModelList()
   * @generated
   */
  EReference getModelList_Getset();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.GetSet <em>Get Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get Set</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.GetSet
   * @generated
   */
  EClass getGetSet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.GetSet#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.GetSet#getName()
   * @see #getGetSet()
   * @generated
   */
  EAttribute getGetSet_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Fragment <em>Fragment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fragment</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Fragment
   * @generated
   */
  EClass getFragment();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.Fragment#getActivityAttributes <em>Activity Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Activity Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Fragment#getActivityAttributes()
   * @see #getFragment()
   * @generated
   */
  EReference getFragment_ActivityAttributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Activity <em>Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Activity</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Activity
   * @generated
   */
  EClass getActivity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.Activity#getActivityTypeAttributes <em>Activity Type Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Activity Type Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Activity#getActivityTypeAttributes()
   * @see #getActivity()
   * @generated
   */
  EReference getActivity_ActivityTypeAttributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.Activity#getActivityAttributes <em>Activity Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Activity Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Activity#getActivityAttributes()
   * @see #getActivity()
   * @generated
   */
  EReference getActivity_ActivityAttributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ActivityTypeAttributes <em>Activity Type Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Activity Type Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ActivityTypeAttributes
   * @generated
   */
  EClass getActivityTypeAttributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.ActivityTypeAttributes#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ActivityTypeAttributes#getFilter()
   * @see #getActivityTypeAttributes()
   * @generated
   */
  EReference getActivityTypeAttributes_Filter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ActivityType <em>Activity Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Activity Type</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ActivityType
   * @generated
   */
  EClass getActivityType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.ActivityLayoutAttributes <em>Activity Layout Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Activity Layout Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ActivityLayoutAttributes
   * @generated
   */
  EClass getActivityLayoutAttributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mdsd.androidGenerator.ActivityLayoutAttributes#getLayoutElements <em>Layout Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layout Elements</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.ActivityLayoutAttributes#getLayoutElements()
   * @see #getActivityLayoutAttributes()
   * @generated
   */
  EReference getActivityLayoutAttributes_LayoutElements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.LayoutElement <em>Layout Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Element</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.LayoutElement
   * @generated
   */
  EClass getLayoutElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.LayoutElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.LayoutElement#getName()
   * @see #getLayoutElement()
   * @generated
   */
  EAttribute getLayoutElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.TextView <em>Text View</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text View</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.TextView
   * @generated
   */
  EClass getTextView();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.FilterQuery <em>Filter Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Query</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.FilterQuery
   * @generated
   */
  EClass getFilterQuery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.FilterQuery#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.FilterQuery#getName()
   * @see #getFilterQuery()
   * @generated
   */
  EAttribute getFilterQuery_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.FilterQuery#getFilterAttributes <em>Filter Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.FilterQuery#getFilterAttributes()
   * @see #getFilterQuery()
   * @generated
   */
  EReference getFilterQuery_FilterAttributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.FilterAttributes <em>Filter Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Attributes</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.FilterAttributes
   * @generated
   */
  EClass getFilterAttributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.FilterAttributes#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Distance</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.FilterAttributes#getDistance()
   * @see #getFilterAttributes()
   * @generated
   */
  EReference getFilterAttributes_Distance();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Distance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distance</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Distance
   * @generated
   */
  EClass getDistance();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.Distance#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Unit</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Distance#getUnit()
   * @see #getDistance()
   * @generated
   */
  EReference getDistance_Unit();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.Distance#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Distance#getOperator()
   * @see #getDistance()
   * @generated
   */
  EReference getDistance_Operator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mdsd.androidGenerator.Distance#getResults <em>Results</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Results</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Distance#getResults()
   * @see #getDistance()
   * @generated
   */
  EReference getDistance_Results();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mdsd.androidGenerator.Number#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Number#getValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Unit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unit</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Unit
   * @generated
   */
  EClass getUnit();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.TypeMap <em>Type Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Map</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.TypeMap
   * @generated
   */
  EClass getTypeMap();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Less <em>Less</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Less
   * @generated
   */
  EClass getLess();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.More <em>More</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>More</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.More
   * @generated
   */
  EClass getMore();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Meters <em>Meters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meters</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Meters
   * @generated
   */
  EClass getMeters();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mdsd.androidGenerator.Imperial <em>Imperial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Imperial</em>'.
   * @see org.xtext.example.mdsd.androidGenerator.Imperial
   * @generated
   */
  EClass getImperial();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AndroidGeneratorFactory getAndroidGeneratorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.AndroidAppProjectImpl <em>Android App Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidAppProjectImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getAndroidAppProject()
     * @generated
     */
    EClass ANDROID_APP_PROJECT = eINSTANCE.getAndroidAppProject();

    /**
     * The meta object literal for the '<em><b>Applications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANDROID_APP_PROJECT__APPLICATIONS = eINSTANCE.getAndroidAppProject_Applications();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationImpl <em>Application</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplication()
     * @generated
     */
    EClass APPLICATION = eINSTANCE.getApplication();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPLICATION__NAME = eINSTANCE.getApplication_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION__ATTRIBUTES = eINSTANCE.getApplication_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationAttributeImpl <em>Application Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationAttributeImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationAttribute()
     * @generated
     */
    EClass APPLICATION_ATTRIBUTE = eINSTANCE.getApplicationAttribute();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationVersionImpl <em>Application Version</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationVersionImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationVersion()
     * @generated
     */
    EClass APPLICATION_VERSION = eINSTANCE.getApplicationVersion();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION_VERSION__RESULT = eINSTANCE.getApplicationVersion_Result();

    /**
     * The meta object literal for the '<em><b>Targetsdk</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION_VERSION__TARGETSDK = eINSTANCE.getApplicationVersion_Targetsdk();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TargetSDKImpl <em>Target SDK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.TargetSDKImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getTargetSDK()
     * @generated
     */
    EClass TARGET_SDK = eINSTANCE.getTargetSDK();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_SDK__RESULT = eINSTANCE.getTargetSDK_Result();

    /**
     * The meta object literal for the '<em><b>Minsdk</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET_SDK__MINSDK = eINSTANCE.getTargetSDK_Minsdk();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.MinSDKImpl <em>Min SDK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.MinSDKImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getMinSDK()
     * @generated
     */
    EClass MIN_SDK = eINSTANCE.getMinSDK();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MIN_SDK__RESULT = eINSTANCE.getMinSDK_Result();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationPermissionListImpl <em>Application Permission List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationPermissionListImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationPermissionList()
     * @generated
     */
    EClass APPLICATION_PERMISSION_LIST = eINSTANCE.getApplicationPermissionList();

    /**
     * The meta object literal for the '<em><b>Permissions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION_PERMISSION_LIST__PERMISSIONS = eINSTANCE.getApplicationPermissionList_Permissions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.PermissionImpl <em>Permission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.PermissionImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getPermission()
     * @generated
     */
    EClass PERMISSION = eINSTANCE.getPermission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION__NAME = eINSTANCE.getPermission_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementListImpl <em>Application Element List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementListImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationElementList()
     * @generated
     */
    EClass APPLICATION_ELEMENT_LIST = eINSTANCE.getApplicationElementList();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION_ELEMENT_LIST__ELEMENTS = eINSTANCE.getApplicationElementList_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationMainActivityImpl <em>Application Main Activity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationMainActivityImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationMainActivity()
     * @generated
     */
    EClass APPLICATION_MAIN_ACTIVITY = eINSTANCE.getApplicationMainActivity();

    /**
     * The meta object literal for the '<em><b>Launcher Activity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION_MAIN_ACTIVITY__LAUNCHER_ACTIVITY = eINSTANCE.getApplicationMainActivity_LauncherActivity();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementImpl <em>Application Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ApplicationElementImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getApplicationElement()
     * @generated
     */
    EClass APPLICATION_ELEMENT = eINSTANCE.getApplicationElement();

    /**
     * The meta object literal for the '<em><b>Activity Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION_ELEMENT__ACTIVITY_TYPE = eINSTANCE.getApplicationElement_ActivityType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPLICATION_ELEMENT__NAME = eINSTANCE.getApplicationElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ModelImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Modellist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODELLIST = eINSTANCE.getModel_Modellist();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ModelListImpl <em>Model List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ModelListImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getModelList()
     * @generated
     */
    EClass MODEL_LIST = eINSTANCE.getModelList();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL_LIST__TYPE = eINSTANCE.getModelList_Type();

    /**
     * The meta object literal for the '<em><b>Getset</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL_LIST__GETSET = eINSTANCE.getModelList_Getset();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.GetSetImpl <em>Get Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.GetSetImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getGetSet()
     * @generated
     */
    EClass GET_SET = eINSTANCE.getGetSet();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GET_SET__NAME = eINSTANCE.getGetSet_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.TypeImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.FragmentImpl <em>Fragment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.FragmentImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getFragment()
     * @generated
     */
    EClass FRAGMENT = eINSTANCE.getFragment();

    /**
     * The meta object literal for the '<em><b>Activity Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAGMENT__ACTIVITY_ATTRIBUTES = eINSTANCE.getFragment_ActivityAttributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityImpl <em>Activity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivity()
     * @generated
     */
    EClass ACTIVITY = eINSTANCE.getActivity();

    /**
     * The meta object literal for the '<em><b>Activity Type Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES = eINSTANCE.getActivity_ActivityTypeAttributes();

    /**
     * The meta object literal for the '<em><b>Activity Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVITY__ACTIVITY_ATTRIBUTES = eINSTANCE.getActivity_ActivityAttributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeAttributesImpl <em>Activity Type Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeAttributesImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivityTypeAttributes()
     * @generated
     */
    EClass ACTIVITY_TYPE_ATTRIBUTES = eINSTANCE.getActivityTypeAttributes();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVITY_TYPE_ATTRIBUTES__FILTER = eINSTANCE.getActivityTypeAttributes_Filter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeImpl <em>Activity Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityTypeImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivityType()
     * @generated
     */
    EClass ACTIVITY_TYPE = eINSTANCE.getActivityType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityLayoutAttributesImpl <em>Activity Layout Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ActivityLayoutAttributesImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getActivityLayoutAttributes()
     * @generated
     */
    EClass ACTIVITY_LAYOUT_ATTRIBUTES = eINSTANCE.getActivityLayoutAttributes();

    /**
     * The meta object literal for the '<em><b>Layout Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS = eINSTANCE.getActivityLayoutAttributes_LayoutElements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.LayoutElementImpl <em>Layout Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.LayoutElementImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getLayoutElement()
     * @generated
     */
    EClass LAYOUT_ELEMENT = eINSTANCE.getLayoutElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYOUT_ELEMENT__NAME = eINSTANCE.getLayoutElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TextViewImpl <em>Text View</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.TextViewImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getTextView()
     * @generated
     */
    EClass TEXT_VIEW = eINSTANCE.getTextView();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ButtonImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.FilterQueryImpl <em>Filter Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.FilterQueryImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getFilterQuery()
     * @generated
     */
    EClass FILTER_QUERY = eINSTANCE.getFilterQuery();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILTER_QUERY__NAME = eINSTANCE.getFilterQuery_Name();

    /**
     * The meta object literal for the '<em><b>Filter Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER_QUERY__FILTER_ATTRIBUTES = eINSTANCE.getFilterQuery_FilterAttributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.FilterAttributesImpl <em>Filter Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.FilterAttributesImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getFilterAttributes()
     * @generated
     */
    EClass FILTER_ATTRIBUTES = eINSTANCE.getFilterAttributes();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER_ATTRIBUTES__DISTANCE = eINSTANCE.getFilterAttributes_Distance();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.DistanceImpl <em>Distance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.DistanceImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getDistance()
     * @generated
     */
    EClass DISTANCE = eINSTANCE.getDistance();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTANCE__UNIT = eINSTANCE.getDistance_Unit();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTANCE__OPERATOR = eINSTANCE.getDistance_Operator();

    /**
     * The meta object literal for the '<em><b>Results</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTANCE__RESULTS = eINSTANCE.getDistance_Results();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.NumberImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__VALUE = eINSTANCE.getNumber_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.OperatorImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.UnitImpl <em>Unit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.UnitImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getUnit()
     * @generated
     */
    EClass UNIT = eINSTANCE.getUnit();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.TypeMapImpl <em>Type Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.TypeMapImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getTypeMap()
     * @generated
     */
    EClass TYPE_MAP = eINSTANCE.getTypeMap();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.LessImpl <em>Less</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.LessImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getLess()
     * @generated
     */
    EClass LESS = eINSTANCE.getLess();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.MoreImpl <em>More</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.MoreImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getMore()
     * @generated
     */
    EClass MORE = eINSTANCE.getMore();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.EqualImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.MetersImpl <em>Meters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.MetersImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getMeters()
     * @generated
     */
    EClass METERS = eINSTANCE.getMeters();

    /**
     * The meta object literal for the '{@link org.xtext.example.mdsd.androidGenerator.impl.ImperialImpl <em>Imperial</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mdsd.androidGenerator.impl.ImperialImpl
     * @see org.xtext.example.mdsd.androidGenerator.impl.AndroidGeneratorPackageImpl#getImperial()
     * @generated
     */
    EClass IMPERIAL = eINSTANCE.getImperial();

  }

} //AndroidGeneratorPackage
