/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application Main Activity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.ApplicationMainActivity#getLauncherActivity <em>Launcher Activity</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage#getApplicationMainActivity()
 * @model
 * @generated
 */
public interface ApplicationMainActivity extends ApplicationAttribute
{
  /**
   * Returns the value of the '<em><b>Launcher Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Launcher Activity</em>' reference.
   * @see #setLauncherActivity(Activity)
   * @see org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage#getApplicationMainActivity_LauncherActivity()
   * @model
   * @generated
   */
  Activity getLauncherActivity();

  /**
   * Sets the value of the '{@link org.xtext.example.mdsd.androidGenerator.ApplicationMainActivity#getLauncherActivity <em>Launcher Activity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Launcher Activity</em>' reference.
   * @see #getLauncherActivity()
   * @generated
   */
  void setLauncherActivity(Activity value);

} // ApplicationMainActivity
