/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage#getEqual()
 * @model
 * @generated
 */
public interface Equal extends Operator
{
} // Equal
