/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mdsd.AndroidGeneratorRuntimeModule;
import org.xtext.example.mdsd.AndroidGeneratorStandaloneSetup;
import org.xtext.example.mdsd.ide.AndroidGeneratorIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AndroidGeneratorIdeSetup extends AndroidGeneratorStandaloneSetup {
  @Override
  public Injector createInjector() {
    AndroidGeneratorRuntimeModule _androidGeneratorRuntimeModule = new AndroidGeneratorRuntimeModule();
    AndroidGeneratorIdeModule _androidGeneratorIdeModule = new AndroidGeneratorIdeModule();
    return Guice.createInjector(Modules2.mixin(_androidGeneratorRuntimeModule, _androidGeneratorIdeModule));
  }
}
