/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AndroidGeneratorStandaloneSetup extends AndroidGeneratorStandaloneSetupGenerated {

	public static void doSetup() {
		new AndroidGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
