/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AndroidGeneratorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class AndroidAppProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.AndroidAppProject");
		private final Assignment cApplicationsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cApplicationsApplicationParserRuleCall_0 = (RuleCall)cApplicationsAssignment.eContents().get(0);
		
		//AndroidAppProject:
		//	applications+=Application*;
		@Override public ParserRule getRule() { return rule; }
		
		//applications+=Application*
		public Assignment getApplicationsAssignment() { return cApplicationsAssignment; }
		
		//Application
		public RuleCall getApplicationsApplicationParserRuleCall_0() { return cApplicationsApplicationParserRuleCall_0; }
	}
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAppKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cAttributesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAttributesApplicationAttributeParserRuleCall_2_0 = (RuleCall)cAttributesAssignment_2.eContents().get(0);
		
		//Application:
		//	'App' name=ID attributes+=ApplicationAttribute*;
		@Override public ParserRule getRule() { return rule; }
		
		//'App' name=ID attributes+=ApplicationAttribute*
		public Group getGroup() { return cGroup; }
		
		//'App'
		public Keyword getAppKeyword_0() { return cAppKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//attributes+=ApplicationAttribute*
		public Assignment getAttributesAssignment_2() { return cAttributesAssignment_2; }
		
		//ApplicationAttribute
		public RuleCall getAttributesApplicationAttributeParserRuleCall_2_0() { return cAttributesApplicationAttributeParserRuleCall_2_0; }
	}
	public class ApplicationAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.ApplicationAttribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cApplicationVersionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cApplicationPermissionListParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cApplicationElementListParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ApplicationAttribute:
		//	ApplicationVersion | ApplicationPermissionList | ApplicationElementList;
		@Override public ParserRule getRule() { return rule; }
		
		//ApplicationVersion | ApplicationPermissionList | ApplicationElementList
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ApplicationVersion
		public RuleCall getApplicationVersionParserRuleCall_0() { return cApplicationVersionParserRuleCall_0; }
		
		//ApplicationPermissionList
		public RuleCall getApplicationPermissionListParserRuleCall_1() { return cApplicationPermissionListParserRuleCall_1; }
		
		//ApplicationElementList
		public RuleCall getApplicationElementListParserRuleCall_2() { return cApplicationElementListParserRuleCall_2; }
	}
	public class ApplicationVersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.ApplicationVersion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cApplicationVersionAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cAndroidSDKKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cResultAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cResultNumberParserRuleCall_4_0 = (RuleCall)cResultAssignment_4.eContents().get(0);
		private final Assignment cTargetsdkAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTargetsdkTargetSDKParserRuleCall_5_0 = (RuleCall)cTargetsdkAssignment_5.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		
		//ApplicationVersion:
		//	{ApplicationVersion} BEGIN 'Android-SDK' ':' result=Number targetsdk=TargetSDK? END;
		@Override public ParserRule getRule() { return rule; }
		
		//{ApplicationVersion} BEGIN 'Android-SDK' ':' result=Number targetsdk=TargetSDK? END
		public Group getGroup() { return cGroup; }
		
		//{ApplicationVersion}
		public Action getApplicationVersionAction_0() { return cApplicationVersionAction_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_1() { return cBEGINTerminalRuleCall_1; }
		
		//'Android-SDK'
		public Keyword getAndroidSDKKeyword_2() { return cAndroidSDKKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//result=Number
		public Assignment getResultAssignment_4() { return cResultAssignment_4; }
		
		//Number
		public RuleCall getResultNumberParserRuleCall_4_0() { return cResultNumberParserRuleCall_4_0; }
		
		//targetsdk=TargetSDK?
		public Assignment getTargetsdkAssignment_5() { return cTargetsdkAssignment_5; }
		
		//TargetSDK
		public RuleCall getTargetsdkTargetSDKParserRuleCall_5_0() { return cTargetsdkTargetSDKParserRuleCall_5_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_6() { return cENDTerminalRuleCall_6; }
	}
	public class TargetSDKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.TargetSDK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTargetSDKAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTargetSDKKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cResultAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cResultNumberParserRuleCall_3_0 = (RuleCall)cResultAssignment_3.eContents().get(0);
		private final Assignment cMinsdkAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMinsdkMinSDKParserRuleCall_4_0 = (RuleCall)cMinsdkAssignment_4.eContents().get(0);
		
		//TargetSDK:
		//	{TargetSDK} 'Target-SDK' ':' result=Number minsdk=MinSDK?;
		@Override public ParserRule getRule() { return rule; }
		
		//{TargetSDK} 'Target-SDK' ':' result=Number minsdk=MinSDK?
		public Group getGroup() { return cGroup; }
		
		//{TargetSDK}
		public Action getTargetSDKAction_0() { return cTargetSDKAction_0; }
		
		//'Target-SDK'
		public Keyword getTargetSDKKeyword_1() { return cTargetSDKKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//result=Number
		public Assignment getResultAssignment_3() { return cResultAssignment_3; }
		
		//Number
		public RuleCall getResultNumberParserRuleCall_3_0() { return cResultNumberParserRuleCall_3_0; }
		
		//minsdk=MinSDK?
		public Assignment getMinsdkAssignment_4() { return cMinsdkAssignment_4; }
		
		//MinSDK
		public RuleCall getMinsdkMinSDKParserRuleCall_4_0() { return cMinsdkMinSDKParserRuleCall_4_0; }
	}
	public class MinSDKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.MinSDK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMinSDKAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMinSDKKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cResultAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cResultNumberParserRuleCall_3_0 = (RuleCall)cResultAssignment_3.eContents().get(0);
		
		//MinSDK:
		//	{MinSDK} 'Min-SDK' ':' result=Number;
		@Override public ParserRule getRule() { return rule; }
		
		//{MinSDK} 'Min-SDK' ':' result=Number
		public Group getGroup() { return cGroup; }
		
		//{MinSDK}
		public Action getMinSDKAction_0() { return cMinSDKAction_0; }
		
		//'Min-SDK'
		public Keyword getMinSDKKeyword_1() { return cMinSDKKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//result=Number
		public Assignment getResultAssignment_3() { return cResultAssignment_3; }
		
		//Number
		public RuleCall getResultNumberParserRuleCall_3_0() { return cResultNumberParserRuleCall_3_0; }
	}
	public class ApplicationPermissionListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.ApplicationPermissionList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPermissionsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPermissionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPermissionsPermissionParserRuleCall_1_0 = (RuleCall)cPermissionsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPermissionsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPermissionsPermissionParserRuleCall_2_1_0 = (RuleCall)cPermissionsAssignment_2_1.eContents().get(0);
		
		//ApplicationPermissionList:
		//	'Permissions' permissions+=Permission (',' permissions+=Permission)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Permissions' permissions+=Permission (',' permissions+=Permission)*
		public Group getGroup() { return cGroup; }
		
		//'Permissions'
		public Keyword getPermissionsKeyword_0() { return cPermissionsKeyword_0; }
		
		//permissions+=Permission
		public Assignment getPermissionsAssignment_1() { return cPermissionsAssignment_1; }
		
		//Permission
		public RuleCall getPermissionsPermissionParserRuleCall_1_0() { return cPermissionsPermissionParserRuleCall_1_0; }
		
		//(',' permissions+=Permission)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//permissions+=Permission
		public Assignment getPermissionsAssignment_2_1() { return cPermissionsAssignment_2_1; }
		
		//Permission
		public RuleCall getPermissionsPermissionParserRuleCall_2_1_0() { return cPermissionsPermissionParserRuleCall_2_1_0; }
	}
	public class PermissionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Permission");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNamePACKAGE_NAMETerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Permission:
		//	name=PACKAGE_NAME // android permissions are in packagename fortmat (e.g. "android.permission.INTERNET")
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=PACKAGE_NAME
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//PACKAGE_NAME
		public RuleCall getNamePACKAGE_NAMETerminalRuleCall_0() { return cNamePACKAGE_NAMETerminalRuleCall_0; }
	}
	public class ApplicationElementListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.ApplicationElementList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cApplicationElementListAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cElementsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cBEGINTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cElementsApplicationElementParserRuleCall_3_0 = (RuleCall)cElementsAssignment_3.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//ApplicationElementList:
		//	{ApplicationElementList} 'Elements' BEGIN elements+=ApplicationElement* END;
		@Override public ParserRule getRule() { return rule; }
		
		//{ApplicationElementList} 'Elements' BEGIN elements+=ApplicationElement* END
		public Group getGroup() { return cGroup; }
		
		//{ApplicationElementList}
		public Action getApplicationElementListAction_0() { return cApplicationElementListAction_0; }
		
		//'Elements'
		public Keyword getElementsKeyword_1() { return cElementsKeyword_1; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2() { return cBEGINTerminalRuleCall_2; }
		
		//elements+=ApplicationElement*
		public Assignment getElementsAssignment_3() { return cElementsAssignment_3; }
		
		//ApplicationElement
		public RuleCall getElementsApplicationElementParserRuleCall_3_0() { return cElementsApplicationElementParserRuleCall_3_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_4() { return cENDTerminalRuleCall_4; }
	}
	public class ApplicationElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.ApplicationElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFragmentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cModelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ApplicationElement:
		//	Fragment | Model;
		@Override public ParserRule getRule() { return rule; }
		
		//Fragment | Model
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Fragment
		public RuleCall getFragmentParserRuleCall_0() { return cFragmentParserRuleCall_0; }
		
		//Model
		public RuleCall getModelParserRuleCall_1() { return cModelParserRuleCall_1; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Model:
		//	'Model' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'Model' name=ID
		public Group getGroup() { return cGroup; }
		
		//'Model'
		public Keyword getModelKeyword_0() { return cModelKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class FragmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Fragment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFragmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cFragmentAttributesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFragmentAttributesFragmentLayoutAttributesParserRuleCall_2_0 = (RuleCall)cFragmentAttributesAssignment_2.eContents().get(0);
		
		//Fragment:
		//	'Fragment' name=ID fragmentAttributes+=FragmentLayoutAttributes?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Fragment' name=ID fragmentAttributes+=FragmentLayoutAttributes?
		public Group getGroup() { return cGroup; }
		
		//'Fragment'
		public Keyword getFragmentKeyword_0() { return cFragmentKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//fragmentAttributes+=FragmentLayoutAttributes?
		public Assignment getFragmentAttributesAssignment_2() { return cFragmentAttributesAssignment_2; }
		
		//FragmentLayoutAttributes
		public RuleCall getFragmentAttributesFragmentLayoutAttributesParserRuleCall_2_0() { return cFragmentAttributesFragmentLayoutAttributesParserRuleCall_2_0; }
	}
	public class FragmentLayoutAttributesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.FragmentLayoutAttributes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBEGINTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cLayoutElementsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLayoutElementsLayoutElementParserRuleCall_1_0 = (RuleCall)cLayoutElementsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLayoutElementsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLayoutElementsLayoutElementParserRuleCall_2_1_0 = (RuleCall)cLayoutElementsAssignment_2_1.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//FragmentLayoutAttributes:
		//	BEGIN layoutElements+=LayoutElement (',' layoutElements+=LayoutElement)* END;
		@Override public ParserRule getRule() { return rule; }
		
		//BEGIN layoutElements+=LayoutElement (',' layoutElements+=LayoutElement)* END
		public Group getGroup() { return cGroup; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_0() { return cBEGINTerminalRuleCall_0; }
		
		//layoutElements+=LayoutElement
		public Assignment getLayoutElementsAssignment_1() { return cLayoutElementsAssignment_1; }
		
		//LayoutElement
		public RuleCall getLayoutElementsLayoutElementParserRuleCall_1_0() { return cLayoutElementsLayoutElementParserRuleCall_1_0; }
		
		//(',' layoutElements+=LayoutElement)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//layoutElements+=LayoutElement
		public Assignment getLayoutElementsAssignment_2_1() { return cLayoutElementsAssignment_2_1; }
		
		//LayoutElement
		public RuleCall getLayoutElementsLayoutElementParserRuleCall_2_1_0() { return cLayoutElementsLayoutElementParserRuleCall_2_1_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_3() { return cENDTerminalRuleCall_3; }
	}
	public class LayoutElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.LayoutElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cButtonParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDataholdersParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTypeMapParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTypeSettingParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//LayoutElement:
		//	Button | Dataholders | TypeMap | TypeSetting;
		@Override public ParserRule getRule() { return rule; }
		
		//Button | Dataholders | TypeMap | TypeSetting
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Button
		public RuleCall getButtonParserRuleCall_0() { return cButtonParserRuleCall_0; }
		
		//Dataholders
		public RuleCall getDataholdersParserRuleCall_1() { return cDataholdersParserRuleCall_1; }
		
		//TypeMap
		public RuleCall getTypeMapParserRuleCall_2() { return cTypeMapParserRuleCall_2; }
		
		//TypeSetting
		public RuleCall getTypeSettingParserRuleCall_3() { return cTypeSettingParserRuleCall_3; }
	}
	public class DataholdersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Dataholders");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEditTextParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSpinnerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextViewParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Dataholders:
		//	EditText | Spinner | TextView;
		@Override public ParserRule getRule() { return rule; }
		
		//EditText | Spinner | TextView
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EditText
		public RuleCall getEditTextParserRuleCall_0() { return cEditTextParserRuleCall_0; }
		
		//Spinner
		public RuleCall getSpinnerParserRuleCall_1() { return cSpinnerParserRuleCall_1; }
		
		//TextView
		public RuleCall getTextViewParserRuleCall_2() { return cTextViewParserRuleCall_2; }
	}
	public class TypeMapElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.TypeMap");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeMapAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMapKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFragmenttypeattributeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFragmenttypeattributeFragmentTypeAttributesParserRuleCall_2_0 = (RuleCall)cFragmenttypeattributeAssignment_2.eContents().get(0);
		
		//TypeMap:
		//	{TypeMap} 'Map' fragmenttypeattribute=FragmentTypeAttributes?;
		@Override public ParserRule getRule() { return rule; }
		
		//{TypeMap} 'Map' fragmenttypeattribute=FragmentTypeAttributes?
		public Group getGroup() { return cGroup; }
		
		//{TypeMap}
		public Action getTypeMapAction_0() { return cTypeMapAction_0; }
		
		//'Map'
		public Keyword getMapKeyword_1() { return cMapKeyword_1; }
		
		//fragmenttypeattribute=FragmentTypeAttributes?
		public Assignment getFragmenttypeattributeAssignment_2() { return cFragmenttypeattributeAssignment_2; }
		
		//FragmentTypeAttributes
		public RuleCall getFragmenttypeattributeFragmentTypeAttributesParserRuleCall_2_0() { return cFragmenttypeattributeFragmentTypeAttributesParserRuleCall_2_0; }
	}
	public class TypeSettingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.TypeSetting");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeSettingAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSettingsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//TypeSetting:
		//	{TypeSetting} 'Settings';
		@Override public ParserRule getRule() { return rule; }
		
		//{TypeSetting} 'Settings'
		public Group getGroup() { return cGroup; }
		
		//{TypeSetting}
		public Action getTypeSettingAction_0() { return cTypeSettingAction_0; }
		
		//'Settings'
		public Keyword getSettingsKeyword_1() { return cSettingsKeyword_1; }
	}
	public class FragmentTypeAttributesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.FragmentTypeAttributes");
		private final Assignment cFilterAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFilterFilterQueryParserRuleCall_0 = (RuleCall)cFilterAssignment.eContents().get(0);
		
		//FragmentTypeAttributes:
		//	filter=FilterQuery;
		@Override public ParserRule getRule() { return rule; }
		
		//filter=FilterQuery
		public Assignment getFilterAssignment() { return cFilterAssignment; }
		
		//FilterQuery
		public RuleCall getFilterFilterQueryParserRuleCall_0() { return cFilterFilterQueryParserRuleCall_0; }
	}
	public class EditTextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.EditText");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEditTextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//EditText:
		//	'EditText' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'EditText' name=ID
		public Group getGroup() { return cGroup; }
		
		//'EditText'
		public Keyword getEditTextKeyword_0() { return cEditTextKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class SpinnerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Spinner");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSpinnerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cContentKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cSpinnerconAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cSpinnerconSpinnerConParserRuleCall_2_2_0 = (RuleCall)cSpinnerconAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cSpinnerconAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cSpinnerconSpinnerConParserRuleCall_2_3_1_0 = (RuleCall)cSpinnerconAssignment_2_3_1.eContents().get(0);
		
		//Spinner:
		//	'Spinner' name=ID ('Content' ':' spinnercon+=SpinnerCon (',' spinnercon+=SpinnerCon)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Spinner' name=ID ('Content' ':' spinnercon+=SpinnerCon (',' spinnercon+=SpinnerCon)*)?
		public Group getGroup() { return cGroup; }
		
		//'Spinner'
		public Keyword getSpinnerKeyword_0() { return cSpinnerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('Content' ':' spinnercon+=SpinnerCon (',' spinnercon+=SpinnerCon)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Content'
		public Keyword getContentKeyword_2_0() { return cContentKeyword_2_0; }
		
		//':'
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }
		
		//spinnercon+=SpinnerCon
		public Assignment getSpinnerconAssignment_2_2() { return cSpinnerconAssignment_2_2; }
		
		//SpinnerCon
		public RuleCall getSpinnerconSpinnerConParserRuleCall_2_2_0() { return cSpinnerconSpinnerConParserRuleCall_2_2_0; }
		
		//(',' spinnercon+=SpinnerCon)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//','
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//spinnercon+=SpinnerCon
		public Assignment getSpinnerconAssignment_2_3_1() { return cSpinnerconAssignment_2_3_1; }
		
		//SpinnerCon
		public RuleCall getSpinnerconSpinnerConParserRuleCall_2_3_1_0() { return cSpinnerconSpinnerConParserRuleCall_2_3_1_0; }
	}
	public class SpinnerConElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.SpinnerCon");
		private final Assignment cTextAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_0 = (RuleCall)cTextAssignment.eContents().get(0);
		
		//SpinnerCon:
		//	text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//text=STRING
		public Assignment getTextAssignment() { return cTextAssignment; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_0() { return cTextSTRINGTerminalRuleCall_0; }
	}
	public class TextViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.TextView");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextviewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cContentKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_0 = (RuleCall)cTextAssignment_4.eContents().get(0);
		
		//TextView:
		//	'Textview' name=ID 'Content' ':' text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Textview' name=ID 'Content' ':' text=STRING
		public Group getGroup() { return cGroup; }
		
		//'Textview'
		public Keyword getTextviewKeyword_0() { return cTextviewKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'Content'
		public Keyword getContentKeyword_2() { return cContentKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//text=STRING
		public Assignment getTextAssignment_4() { return cTextAssignment_4; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_0() { return cTextSTRINGTerminalRuleCall_4_0; }
	}
	public class ButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Button");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cButtonAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cButtonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cActionsAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cActionsButtonActionsParserRuleCall_4_0_0 = (RuleCall)cActionsAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cActionsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cActionsButtonActionsParserRuleCall_4_1_1_0 = (RuleCall)cActionsAssignment_4_1_1.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//Button:
		//	{Button} 'Button' name=ID BEGIN (actions+=ButtonActions (',' actions+=ButtonActions)*)? END;
		@Override public ParserRule getRule() { return rule; }
		
		//{Button} 'Button' name=ID BEGIN (actions+=ButtonActions (',' actions+=ButtonActions)*)? END
		public Group getGroup() { return cGroup; }
		
		//{Button}
		public Action getButtonAction_0() { return cButtonAction_0; }
		
		//'Button'
		public Keyword getButtonKeyword_1() { return cButtonKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_3() { return cBEGINTerminalRuleCall_3; }
		
		//(actions+=ButtonActions (',' actions+=ButtonActions)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//actions+=ButtonActions
		public Assignment getActionsAssignment_4_0() { return cActionsAssignment_4_0; }
		
		//ButtonActions
		public RuleCall getActionsButtonActionsParserRuleCall_4_0_0() { return cActionsButtonActionsParserRuleCall_4_0_0; }
		
		//(',' actions+=ButtonActions)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//','
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//actions+=ButtonActions
		public Assignment getActionsAssignment_4_1_1() { return cActionsAssignment_4_1_1; }
		
		//ButtonActions
		public RuleCall getActionsButtonActionsParserRuleCall_4_1_1_0() { return cActionsButtonActionsParserRuleCall_4_1_1_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_5() { return cENDTerminalRuleCall_5; }
	}
	public class ButtonActionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.ButtonActions");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cToastParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBundleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ButtonActions:
		//	Toast | Bundle;
		@Override public ParserRule getRule() { return rule; }
		
		//Toast | Bundle
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Toast
		public RuleCall getToastParserRuleCall_0() { return cToastParserRuleCall_0; }
		
		//Bundle
		public RuleCall getBundleParserRuleCall_1() { return cBundleParserRuleCall_1; }
	}
	public class ToastElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Toast");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cToastKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Toast:
		//	'Toast' text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Toast' text=STRING
		public Group getGroup() { return cGroup; }
		
		//'Toast'
		public Keyword getToastKeyword_0() { return cToastKeyword_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
	}
	public class BundleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Bundle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBundleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBundleRecipientAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cBundleRecipientFragmentCrossReference_1_0 = (CrossReference)cBundleRecipientAssignment_1.eContents().get(0);
		private final RuleCall cBundleRecipientFragmentIDTerminalRuleCall_1_0_1 = (RuleCall)cBundleRecipientFragmentCrossReference_1_0.eContents().get(1);
		private final Assignment cHolderAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cHolderHolderParserRuleCall_2_0 = (RuleCall)cHolderAssignment_2.eContents().get(0);
		
		//Bundle:
		//	'Bundle' bundleRecipient=[Fragment] holder=Holder?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Bundle' bundleRecipient=[Fragment] holder=Holder?
		public Group getGroup() { return cGroup; }
		
		//'Bundle'
		public Keyword getBundleKeyword_0() { return cBundleKeyword_0; }
		
		//bundleRecipient=[Fragment]
		public Assignment getBundleRecipientAssignment_1() { return cBundleRecipientAssignment_1; }
		
		//[Fragment]
		public CrossReference getBundleRecipientFragmentCrossReference_1_0() { return cBundleRecipientFragmentCrossReference_1_0; }
		
		//ID
		public RuleCall getBundleRecipientFragmentIDTerminalRuleCall_1_0_1() { return cBundleRecipientFragmentIDTerminalRuleCall_1_0_1; }
		
		//holder=Holder?
		public Assignment getHolderAssignment_2() { return cHolderAssignment_2; }
		
		//Holder
		public RuleCall getHolderHolderParserRuleCall_2_0() { return cHolderHolderParserRuleCall_2_0; }
	}
	public class HolderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Holder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHolderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHolAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cHolDataholdersCrossReference_1_0 = (CrossReference)cHolAssignment_1.eContents().get(0);
		private final RuleCall cHolDataholdersIDTerminalRuleCall_1_0_1 = (RuleCall)cHolDataholdersCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cHolAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cHolDataholdersCrossReference_2_1_0 = (CrossReference)cHolAssignment_2_1.eContents().get(0);
		private final RuleCall cHolDataholdersIDTerminalRuleCall_2_1_0_1 = (RuleCall)cHolDataholdersCrossReference_2_1_0.eContents().get(1);
		
		//Holder:
		//	'Holder' hol+=[Dataholders] (',' hol+=[Dataholders])*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Holder' hol+=[Dataholders] (',' hol+=[Dataholders])*
		public Group getGroup() { return cGroup; }
		
		//'Holder'
		public Keyword getHolderKeyword_0() { return cHolderKeyword_0; }
		
		//hol+=[Dataholders]
		public Assignment getHolAssignment_1() { return cHolAssignment_1; }
		
		//[Dataholders]
		public CrossReference getHolDataholdersCrossReference_1_0() { return cHolDataholdersCrossReference_1_0; }
		
		//ID
		public RuleCall getHolDataholdersIDTerminalRuleCall_1_0_1() { return cHolDataholdersIDTerminalRuleCall_1_0_1; }
		
		//(',' hol+=[Dataholders])*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//hol+=[Dataholders]
		public Assignment getHolAssignment_2_1() { return cHolAssignment_2_1; }
		
		//[Dataholders]
		public CrossReference getHolDataholdersCrossReference_2_1_0() { return cHolDataholdersCrossReference_2_1_0; }
		
		//ID
		public RuleCall getHolDataholdersIDTerminalRuleCall_2_1_0_1() { return cHolDataholdersIDTerminalRuleCall_2_1_0_1; }
	}
	public class FilterQueryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.FilterQuery");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFilterQueryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFilterQueryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cFilterAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFilterAttributesFilterAttributesParserRuleCall_3_0 = (RuleCall)cFilterAttributesAssignment_3.eContents().get(0);
		
		//FilterQuery:
		//	{FilterQuery} 'FilterQuery' name=ID filterAttributes=FilterAttributes;
		@Override public ParserRule getRule() { return rule; }
		
		//{FilterQuery} 'FilterQuery' name=ID filterAttributes=FilterAttributes
		public Group getGroup() { return cGroup; }
		
		//{FilterQuery}
		public Action getFilterQueryAction_0() { return cFilterQueryAction_0; }
		
		//'FilterQuery'
		public Keyword getFilterQueryKeyword_1() { return cFilterQueryKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//filterAttributes=FilterAttributes
		public Assignment getFilterAttributesAssignment_3() { return cFilterAttributesAssignment_3; }
		
		//FilterAttributes
		public RuleCall getFilterAttributesFilterAttributesParserRuleCall_3_0() { return cFilterAttributesFilterAttributesParserRuleCall_3_0; }
	}
	public class FilterAttributesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.FilterAttributes");
		private final Assignment cDistanceAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDistanceDistanceParserRuleCall_0 = (RuleCall)cDistanceAssignment.eContents().get(0);
		
		//FilterAttributes:
		//	distance=Distance;
		@Override public ParserRule getRule() { return rule; }
		
		//distance=Distance
		public Assignment getDistanceAssignment() { return cDistanceAssignment; }
		
		//Distance
		public RuleCall getDistanceDistanceParserRuleCall_0() { return cDistanceDistanceParserRuleCall_0; }
	}
	public class DistanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Distance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDistKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUnitAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUnitUnitParserRuleCall_2_0 = (RuleCall)cUnitAssignment_2.eContents().get(0);
		private final Assignment cOperatorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperatorOperatorParserRuleCall_3_0 = (RuleCall)cOperatorAssignment_3.eContents().get(0);
		private final Assignment cResultsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cResultsNumberParserRuleCall_4_0 = (RuleCall)cResultsAssignment_4.eContents().get(0);
		
		//Distance:
		//	'Dist' ':' unit=Unit operator=Operator results=Number;
		@Override public ParserRule getRule() { return rule; }
		
		//'Dist' ':' unit=Unit operator=Operator results=Number
		public Group getGroup() { return cGroup; }
		
		//'Dist'
		public Keyword getDistKeyword_0() { return cDistKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//unit=Unit
		public Assignment getUnitAssignment_2() { return cUnitAssignment_2; }
		
		//Unit
		public RuleCall getUnitUnitParserRuleCall_2_0() { return cUnitUnitParserRuleCall_2_0; }
		
		//operator=Operator
		public Assignment getOperatorAssignment_3() { return cOperatorAssignment_3; }
		
		//Operator
		public RuleCall getOperatorOperatorParserRuleCall_3_0() { return cOperatorOperatorParserRuleCall_3_0; }
		
		//results=Number
		public Assignment getResultsAssignment_4() { return cResultsAssignment_4; }
		
		//Number
		public RuleCall getResultsNumberParserRuleCall_4_0() { return cResultsNumberParserRuleCall_4_0; }
	}
	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Number");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Number:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cLessAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cMoreAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cEqualAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		
		//Operator:
		//	{Less} '>' | {More} '<' | {Equal} '=';
		@Override public ParserRule getRule() { return rule; }
		
		//{Less} '>' | {More} '<' | {Equal} '='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Less} '>'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Less}
		public Action getLessAction_0_0() { return cLessAction_0_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_0_1() { return cGreaterThanSignKeyword_0_1; }
		
		//{More} '<'
		public Group getGroup_1() { return cGroup_1; }
		
		//{More}
		public Action getMoreAction_1_0() { return cMoreAction_1_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1_1() { return cLessThanSignKeyword_1_1; }
		
		//{Equal} '='
		public Group getGroup_2() { return cGroup_2; }
		
		//{Equal}
		public Action getEqualAction_2_0() { return cEqualAction_2_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2_1() { return cEqualsSignKeyword_2_1; }
	}
	public class UnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.Unit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cMetersAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cMKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cImperialAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cFKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//Unit:
		//	{Meters} 'm' | {Imperial} 'f';
		@Override public ParserRule getRule() { return rule; }
		
		//{Meters} 'm' | {Imperial} 'f'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Meters} 'm'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Meters}
		public Action getMetersAction_0_0() { return cMetersAction_0_0; }
		
		//'m'
		public Keyword getMKeyword_0_1() { return cMKeyword_0_1; }
		
		//{Imperial} 'f'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Imperial}
		public Action getImperialAction_1_0() { return cImperialAction_1_0; }
		
		//'f'
		public Keyword getFKeyword_1_1() { return cFKeyword_1_1; }
	}
	
	
	private final AndroidAppProjectElements pAndroidAppProject;
	private final ApplicationElements pApplication;
	private final ApplicationAttributeElements pApplicationAttribute;
	private final ApplicationVersionElements pApplicationVersion;
	private final TargetSDKElements pTargetSDK;
	private final MinSDKElements pMinSDK;
	private final ApplicationPermissionListElements pApplicationPermissionList;
	private final PermissionElements pPermission;
	private final ApplicationElementListElements pApplicationElementList;
	private final ApplicationElementElements pApplicationElement;
	private final ModelElements pModel;
	private final FragmentElements pFragment;
	private final FragmentLayoutAttributesElements pFragmentLayoutAttributes;
	private final LayoutElementElements pLayoutElement;
	private final DataholdersElements pDataholders;
	private final TypeMapElements pTypeMap;
	private final TypeSettingElements pTypeSetting;
	private final FragmentTypeAttributesElements pFragmentTypeAttributes;
	private final EditTextElements pEditText;
	private final SpinnerElements pSpinner;
	private final SpinnerConElements pSpinnerCon;
	private final TextViewElements pTextView;
	private final ButtonElements pButton;
	private final ButtonActionsElements pButtonActions;
	private final ToastElements pToast;
	private final BundleElements pBundle;
	private final HolderElements pHolder;
	private final FilterQueryElements pFilterQuery;
	private final FilterAttributesElements pFilterAttributes;
	private final DistanceElements pDistance;
	private final NumberElements pNumber;
	private final OperatorElements pOperator;
	private final UnitElements pUnit;
	private final TerminalRule tBEGIN;
	private final TerminalRule tEND;
	private final TerminalRule tPACKAGE_NAME;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AndroidGeneratorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAndroidAppProject = new AndroidAppProjectElements();
		this.pApplication = new ApplicationElements();
		this.pApplicationAttribute = new ApplicationAttributeElements();
		this.pApplicationVersion = new ApplicationVersionElements();
		this.pTargetSDK = new TargetSDKElements();
		this.pMinSDK = new MinSDKElements();
		this.pApplicationPermissionList = new ApplicationPermissionListElements();
		this.pPermission = new PermissionElements();
		this.pApplicationElementList = new ApplicationElementListElements();
		this.pApplicationElement = new ApplicationElementElements();
		this.pModel = new ModelElements();
		this.pFragment = new FragmentElements();
		this.pFragmentLayoutAttributes = new FragmentLayoutAttributesElements();
		this.pLayoutElement = new LayoutElementElements();
		this.pDataholders = new DataholdersElements();
		this.pTypeMap = new TypeMapElements();
		this.pTypeSetting = new TypeSettingElements();
		this.pFragmentTypeAttributes = new FragmentTypeAttributesElements();
		this.pEditText = new EditTextElements();
		this.pSpinner = new SpinnerElements();
		this.pSpinnerCon = new SpinnerConElements();
		this.pTextView = new TextViewElements();
		this.pButton = new ButtonElements();
		this.pButtonActions = new ButtonActionsElements();
		this.pToast = new ToastElements();
		this.pBundle = new BundleElements();
		this.pHolder = new HolderElements();
		this.pFilterQuery = new FilterQueryElements();
		this.pFilterAttributes = new FilterAttributesElements();
		this.pDistance = new DistanceElements();
		this.pNumber = new NumberElements();
		this.pOperator = new OperatorElements();
		this.pUnit = new UnitElements();
		this.tBEGIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.BEGIN");
		this.tEND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.END");
		this.tPACKAGE_NAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mdsd.AndroidGenerator.PACKAGE_NAME");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mdsd.AndroidGenerator".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//AndroidAppProject:
	//	applications+=Application*;
	public AndroidAppProjectElements getAndroidAppProjectAccess() {
		return pAndroidAppProject;
	}
	
	public ParserRule getAndroidAppProjectRule() {
		return getAndroidAppProjectAccess().getRule();
	}
	
	//Application:
	//	'App' name=ID attributes+=ApplicationAttribute*;
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//ApplicationAttribute:
	//	ApplicationVersion | ApplicationPermissionList | ApplicationElementList;
	public ApplicationAttributeElements getApplicationAttributeAccess() {
		return pApplicationAttribute;
	}
	
	public ParserRule getApplicationAttributeRule() {
		return getApplicationAttributeAccess().getRule();
	}
	
	//ApplicationVersion:
	//	{ApplicationVersion} BEGIN 'Android-SDK' ':' result=Number targetsdk=TargetSDK? END;
	public ApplicationVersionElements getApplicationVersionAccess() {
		return pApplicationVersion;
	}
	
	public ParserRule getApplicationVersionRule() {
		return getApplicationVersionAccess().getRule();
	}
	
	//TargetSDK:
	//	{TargetSDK} 'Target-SDK' ':' result=Number minsdk=MinSDK?;
	public TargetSDKElements getTargetSDKAccess() {
		return pTargetSDK;
	}
	
	public ParserRule getTargetSDKRule() {
		return getTargetSDKAccess().getRule();
	}
	
	//MinSDK:
	//	{MinSDK} 'Min-SDK' ':' result=Number;
	public MinSDKElements getMinSDKAccess() {
		return pMinSDK;
	}
	
	public ParserRule getMinSDKRule() {
		return getMinSDKAccess().getRule();
	}
	
	//ApplicationPermissionList:
	//	'Permissions' permissions+=Permission (',' permissions+=Permission)*;
	public ApplicationPermissionListElements getApplicationPermissionListAccess() {
		return pApplicationPermissionList;
	}
	
	public ParserRule getApplicationPermissionListRule() {
		return getApplicationPermissionListAccess().getRule();
	}
	
	//Permission:
	//	name=PACKAGE_NAME // android permissions are in packagename fortmat (e.g. "android.permission.INTERNET")
	//;
	public PermissionElements getPermissionAccess() {
		return pPermission;
	}
	
	public ParserRule getPermissionRule() {
		return getPermissionAccess().getRule();
	}
	
	//ApplicationElementList:
	//	{ApplicationElementList} 'Elements' BEGIN elements+=ApplicationElement* END;
	public ApplicationElementListElements getApplicationElementListAccess() {
		return pApplicationElementList;
	}
	
	public ParserRule getApplicationElementListRule() {
		return getApplicationElementListAccess().getRule();
	}
	
	//ApplicationElement:
	//	Fragment | Model;
	public ApplicationElementElements getApplicationElementAccess() {
		return pApplicationElement;
	}
	
	public ParserRule getApplicationElementRule() {
		return getApplicationElementAccess().getRule();
	}
	
	//Model:
	//	'Model' name=ID;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Fragment:
	//	'Fragment' name=ID fragmentAttributes+=FragmentLayoutAttributes?;
	public FragmentElements getFragmentAccess() {
		return pFragment;
	}
	
	public ParserRule getFragmentRule() {
		return getFragmentAccess().getRule();
	}
	
	//FragmentLayoutAttributes:
	//	BEGIN layoutElements+=LayoutElement (',' layoutElements+=LayoutElement)* END;
	public FragmentLayoutAttributesElements getFragmentLayoutAttributesAccess() {
		return pFragmentLayoutAttributes;
	}
	
	public ParserRule getFragmentLayoutAttributesRule() {
		return getFragmentLayoutAttributesAccess().getRule();
	}
	
	//LayoutElement:
	//	Button | Dataholders | TypeMap | TypeSetting;
	public LayoutElementElements getLayoutElementAccess() {
		return pLayoutElement;
	}
	
	public ParserRule getLayoutElementRule() {
		return getLayoutElementAccess().getRule();
	}
	
	//Dataholders:
	//	EditText | Spinner | TextView;
	public DataholdersElements getDataholdersAccess() {
		return pDataholders;
	}
	
	public ParserRule getDataholdersRule() {
		return getDataholdersAccess().getRule();
	}
	
	//TypeMap:
	//	{TypeMap} 'Map' fragmenttypeattribute=FragmentTypeAttributes?;
	public TypeMapElements getTypeMapAccess() {
		return pTypeMap;
	}
	
	public ParserRule getTypeMapRule() {
		return getTypeMapAccess().getRule();
	}
	
	//TypeSetting:
	//	{TypeSetting} 'Settings';
	public TypeSettingElements getTypeSettingAccess() {
		return pTypeSetting;
	}
	
	public ParserRule getTypeSettingRule() {
		return getTypeSettingAccess().getRule();
	}
	
	//FragmentTypeAttributes:
	//	filter=FilterQuery;
	public FragmentTypeAttributesElements getFragmentTypeAttributesAccess() {
		return pFragmentTypeAttributes;
	}
	
	public ParserRule getFragmentTypeAttributesRule() {
		return getFragmentTypeAttributesAccess().getRule();
	}
	
	//EditText:
	//	'EditText' name=ID;
	public EditTextElements getEditTextAccess() {
		return pEditText;
	}
	
	public ParserRule getEditTextRule() {
		return getEditTextAccess().getRule();
	}
	
	//Spinner:
	//	'Spinner' name=ID ('Content' ':' spinnercon+=SpinnerCon (',' spinnercon+=SpinnerCon)*)?;
	public SpinnerElements getSpinnerAccess() {
		return pSpinner;
	}
	
	public ParserRule getSpinnerRule() {
		return getSpinnerAccess().getRule();
	}
	
	//SpinnerCon:
	//	text=STRING;
	public SpinnerConElements getSpinnerConAccess() {
		return pSpinnerCon;
	}
	
	public ParserRule getSpinnerConRule() {
		return getSpinnerConAccess().getRule();
	}
	
	//TextView:
	//	'Textview' name=ID 'Content' ':' text=STRING;
	public TextViewElements getTextViewAccess() {
		return pTextView;
	}
	
	public ParserRule getTextViewRule() {
		return getTextViewAccess().getRule();
	}
	
	//Button:
	//	{Button} 'Button' name=ID BEGIN (actions+=ButtonActions (',' actions+=ButtonActions)*)? END;
	public ButtonElements getButtonAccess() {
		return pButton;
	}
	
	public ParserRule getButtonRule() {
		return getButtonAccess().getRule();
	}
	
	//ButtonActions:
	//	Toast | Bundle;
	public ButtonActionsElements getButtonActionsAccess() {
		return pButtonActions;
	}
	
	public ParserRule getButtonActionsRule() {
		return getButtonActionsAccess().getRule();
	}
	
	//Toast:
	//	'Toast' text=STRING;
	public ToastElements getToastAccess() {
		return pToast;
	}
	
	public ParserRule getToastRule() {
		return getToastAccess().getRule();
	}
	
	//Bundle:
	//	'Bundle' bundleRecipient=[Fragment] holder=Holder?;
	public BundleElements getBundleAccess() {
		return pBundle;
	}
	
	public ParserRule getBundleRule() {
		return getBundleAccess().getRule();
	}
	
	//Holder:
	//	'Holder' hol+=[Dataholders] (',' hol+=[Dataholders])*;
	public HolderElements getHolderAccess() {
		return pHolder;
	}
	
	public ParserRule getHolderRule() {
		return getHolderAccess().getRule();
	}
	
	//FilterQuery:
	//	{FilterQuery} 'FilterQuery' name=ID filterAttributes=FilterAttributes;
	public FilterQueryElements getFilterQueryAccess() {
		return pFilterQuery;
	}
	
	public ParserRule getFilterQueryRule() {
		return getFilterQueryAccess().getRule();
	}
	
	//FilterAttributes:
	//	distance=Distance;
	public FilterAttributesElements getFilterAttributesAccess() {
		return pFilterAttributes;
	}
	
	public ParserRule getFilterAttributesRule() {
		return getFilterAttributesAccess().getRule();
	}
	
	//Distance:
	//	'Dist' ':' unit=Unit operator=Operator results=Number;
	public DistanceElements getDistanceAccess() {
		return pDistance;
	}
	
	public ParserRule getDistanceRule() {
		return getDistanceAccess().getRule();
	}
	
	//Number:
	//	value=INT;
	public NumberElements getNumberAccess() {
		return pNumber;
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}
	
	//Operator:
	//	{Less} '>' | {More} '<' | {Equal} '=';
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//Unit:
	//	{Meters} 'm' | {Imperial} 'f';
	public UnitElements getUnitAccess() {
		return pUnit;
	}
	
	public ParserRule getUnitRule() {
		return getUnitAccess().getRule();
	}
	
	//terminal BEGIN:
	//	'synthetic:BEGIN';
	public TerminalRule getBEGINRule() {
		return tBEGIN;
	}
	
	//terminal END:
	//	'synthetic:END';
	public TerminalRule getENDRule() {
		return tEND;
	}
	
	//terminal PACKAGE_NAME:
	//	'"' (ID ('.' ID)*) '"';
	public TerminalRule getPACKAGE_NAMERule() {
		return tPACKAGE_NAME;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
