package org.xtext.example.mdsd.generator.filegen;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.xtext.example.mdsd.androidGenerator.Application;
import org.xtext.example.mdsd.androidGenerator.ApplicationElement;
import org.xtext.example.mdsd.androidGenerator.Model;
import org.xtext.example.mdsd.generator.abstractfiles.AbstractClassGen;

@SuppressWarnings("all")
public class ModelClassGen extends AbstractClassGen {
  @Override
  protected String getSubClassPath() {
    return "model";
  }
  
  @Override
  protected boolean isAllowedElement(final ApplicationElement element) {
    return (element instanceof Model);
  }
  
  @Override
  protected String retrieveElementTemplate(final Application application, final ApplicationElement element) {
    throw new Error("Unresolved compilation problems:"
      + "\nModelList cannot be resolved to a type."
      + "\nModelList cannot be resolved to a type."
      + "\nThe method or field activityAttributes is undefined for the type Model"
      + "\nThe method generateGetSet(ModelList, ApplicationElement, Application) from the type ModelClassGen refers to the missing type ModelList");
  }
  
  private String generateGetSet(final /* ModelList */Object models, final ApplicationElement model, final Application application) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _name = application.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import android.graphics.Bitmap;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("import java.util.logging.Level;");
    _builder.newLine();
    _builder.append("import java.util.logging.Logger;");
    _builder.newLine();
    _builder.append("import org.json.JSONException;");
    _builder.newLine();
    _builder.append("import org.json.JSONObject;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("public class ");
    String _name_1 = model.getName();
    _builder.append(_name_1);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  private String generateMapModel(final Application application) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _name = application.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import android.graphics.Bitmap;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import java.util.logging.Level;");
    _builder.newLine();
    _builder.append("import java.util.logging.Logger;");
    _builder.newLine();
    _builder.append("import org.json.JSONException;");
    _builder.newLine();
    _builder.append("import org.json.JSONObject;");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class Places {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String icon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Double latitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Double longitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Bitmap bitmap;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getId() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setId(String id) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.id = id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getIcon() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return icon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setIcon(String icon) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.icon = icon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setBitmap(Bitmap bitmap) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.bitmap = bitmap;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Bitmap getBitmap() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return bitmap;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Double getLatitude() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return latitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setLatitude(Double latitude) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.latitude = latitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Double getLongitude() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return longitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setLongitude(Double longitude) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.longitude = longitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getName() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setName(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("static Places JSONToResult(JSONObject jsonObject) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (jsonObject != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("Places result = new Places();");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("JSONObject geometry = (JSONObject) jsonObject.get(\"geometry\");");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("JSONObject location = (JSONObject) geometry.get(\"location\");");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setLatitude((Double) location.get(\"lat\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setLongitude((Double) location.get(\"lng\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setIcon(jsonObject.getString(\"icon\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setName(jsonObject.getString(\"name\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setId(jsonObject.getString(\"id\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("return result;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("} catch (JSONException ex) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("Logger.getLogger(Places.class.getName()).log(Level.SEVERE, null, ex);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String toString() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return \"Places{\" + \"id=\" + id + \", icon=\" + icon + \", name=\" + name + \", latitude=\" + latitude + \", longitude=\" + longitude + \'}\';");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
