package org.xtext.example.mdsd.generator.filegen;

import com.google.common.base.Objects;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.xtext.example.mdsd.androidGenerator.ActivityType;
import org.xtext.example.mdsd.androidGenerator.Application;
import org.xtext.example.mdsd.androidGenerator.ApplicationElement;
import org.xtext.example.mdsd.androidGenerator.Model;
import org.xtext.example.mdsd.androidGenerator.ModelList;
import org.xtext.example.mdsd.generator.abstractfiles.AbstractClassGen;

@SuppressWarnings("all")
public class ModelClassGen extends AbstractClassGen {
  @Override
  protected String getSubClassPath() {
    return "model";
  }
  
  @Override
  protected boolean isAllowedElement(final ApplicationElement element) {
    return (element instanceof Model);
  }
  
  @Override
  protected String retrieveElementTemplate(final Application application, final ApplicationElement element) {
    Model model = ((Model) element);
    ModelList modlist = this.<ModelList>getFieldData(application.getAttributes(), ModelList.class);
    ActivityType map = model.getActivityType();
    ModelList mod = model.getModellist();
    boolean isModList = (!Objects.equal(mod, null));
    boolean isMapModel = (!Objects.equal(map, null));
    StringConcatenation _builder = new StringConcatenation();
    {
      if (isMapModel) {
        String _generateMapModel = this.generateMapModel(model, application);
        _builder.append(_generateMapModel);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder.toString();
  }
  
  private String generateGetSet(final ModelList models, final ApplicationElement model, final Application application) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _name = application.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import android.graphics.Bitmap;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("import java.util.logging.Level;");
    _builder.newLine();
    _builder.append("import java.util.logging.Logger;");
    _builder.newLine();
    _builder.append("import org.json.JSONException;");
    _builder.newLine();
    _builder.append("import org.json.JSONObject;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("public class ");
    String _name_1 = model.getName();
    _builder.append(_name_1);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  private String generateMapModel(final ApplicationElement model, final Application application) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _name = application.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import android.graphics.Bitmap;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import java.util.logging.Level;");
    _builder.newLine();
    _builder.append("import java.util.logging.Logger;");
    _builder.newLine();
    _builder.append("import org.json.JSONException;");
    _builder.newLine();
    _builder.append("import org.json.JSONObject;");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    String _name_1 = model.getName();
    _builder.append(_name_1);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("private String id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String icon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Double latitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Double longitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Bitmap bitmap;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getId() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setId(String id) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.id = id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getIcon() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return icon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setIcon(String icon) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.icon = icon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setBitmap(Bitmap bitmap) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.bitmap = bitmap;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Bitmap getBitmap() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return bitmap;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Double getLatitude() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return latitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setLatitude(Double latitude) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.latitude = latitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Double getLongitude() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return longitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setLongitude(Double longitude) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.longitude = longitude;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getName() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setName(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("static ");
    String _name_2 = model.getName();
    _builder.append(_name_2, "    ");
    _builder.append(" JSONToResult(JSONObject jsonObject) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("if (jsonObject != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("                ");
    String _name_3 = model.getName();
    _builder.append(_name_3, "                ");
    _builder.append(" result = new ");
    String _name_4 = model.getName();
    _builder.append(_name_4, "                ");
    _builder.append("();");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("JSONObject geometry = (JSONObject) jsonObject.get(\"geometry\");");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("JSONObject location = (JSONObject) geometry.get(\"location\");");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setLatitude((Double) location.get(\"lat\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setLongitude((Double) location.get(\"lng\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setIcon(jsonObject.getString(\"icon\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setName(jsonObject.getString(\"name\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("result.setId(jsonObject.getString(\"id\"));");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("return result;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("} catch (JSONException ex) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("Logger.getLogger(");
    String _name_5 = model.getName();
    _builder.append(_name_5, "                ");
    _builder.append(".class.getName()).log(Level.SEVERE, null, ex);");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String toString() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return \"");
    String _name_6 = model.getName();
    _builder.append(_name_6, "        ");
    _builder.append("{\" + \"id=\" + id + \", icon=\" + icon + \", name=\" + name + \", latitude=\" + latitude + \", longitude=\" + longitude + \'}\';");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
