package org.xtext.example.mdsd.generator.filegen;

import com.google.common.base.Objects;
import java.util.List;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.xtext.example.mdsd.androidGenerator.Application;
import org.xtext.example.mdsd.androidGenerator.ApplicationVersion;
import org.xtext.example.mdsd.generator.abstractfiles.AbstractGen;

@SuppressWarnings("all")
public class GradleGen extends AbstractGen {
  @Override
  public void generate(final List<Application> applications, final IFileSystemAccess2 filesystem) {
    for (final Application app : applications) {
      {
        String projectName = this.getProjectName(applications, app);
        filesystem.generateFile(String.format("%s/build.gradle", projectName), 
          this.retrieveGradle(app));
      }
    }
  }
  
  public String retrieveGradle(final Application app) {
    ApplicationVersion _fieldData = this.<ApplicationVersion>getFieldData(app.getAttributes(), ApplicationVersion.class);
    boolean _notEquals = (!Objects.equal(_fieldData, null));
    if (_notEquals) {
      final ApplicationVersion ApplicationVersion = this.<org.xtext.example.mdsd.androidGenerator.ApplicationVersion>getFieldData(app.getAttributes(), org.xtext.example.mdsd.androidGenerator.ApplicationVersion.class);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("apply plugin: \'com.android.application\'");
      _builder.newLine();
      _builder.newLine();
      _builder.append("android{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("compileSdkVersion\"");
      int _value = ApplicationVersion.getResult().getValue();
      _builder.append(_value, "\t");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("\t    ");
      _builder.append("buildToolsVersion \"29.0.3\"");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("defaultConfig {");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("applicationId \"");
      String _name = app.getName();
      _builder.append(_name, "\t        ");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("\t        ");
      _builder.append("minSdkVersion \"");
      int _value_1 = ApplicationVersion.getTargetsdk().getMinsdk().getResult().getValue();
      _builder.append(_value_1, "\t        ");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("\t        ");
      _builder.append("targetSdkVersion \"");
      int _value_2 = ApplicationVersion.getTargetsdk().getResult().getValue();
      _builder.append(_value_2, "\t        ");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("\t        ");
      _builder.append("versionCode 1");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("versionName \"1.0\"");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("testInstrumentationRunner \"androidx.test.runner.AndroidJUnitRunner\"");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("buildTypes {");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("release {");
      _builder.newLine();
      _builder.append("\t            ");
      _builder.append("minifyEnabled false");
      _builder.newLine();
      _builder.append("\t            ");
      _builder.append("proguardFiles getDefaultProguardFile(\'proguard-android-optimize.txt\'), \'proguard-rules.pro\'");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dependencies {");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("implementation fileTree(dir: \'libs\', include: [\'*.jar\'])");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("implementation \'androidx.appcompat:appcompat:1.0.2\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("implementation \'androidx.constraintlayout:constraintlayout:1.1.3\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("implementation \'androidx.legacy:legacy-support-v4:1.0.0\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("testImplementation \'junit:junit:4.12\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("androidTestImplementation \'androidx.test.ext:junit:1.1.0\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("androidTestImplementation \'androidx.test.espresso:espresso-core:3.1.1\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("implementation \'com.android.support:design:28.0.0\'");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("implementation \'com.google.android.gms:play-services-maps:16.1.0\'");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      return _builder.toString();
    } else {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("apply plugin: \'com.android.application\'");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("android{");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("compileSdkVersion\"29\"");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("buildToolsVersion \"29.0.3\"");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("defaultConfig {");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("applicationId \"");
      String _name_1 = app.getName();
      _builder_1.append(_name_1, "\t        ");
      _builder_1.append("\"");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("\t        ");
      _builder_1.append("minSdkVersion \"21\"");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("targetSdkVersion \"29\"");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("versionCode 1");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("versionName \"1.0\"");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("testInstrumentationRunner \"androidx.test.runner.AndroidJUnitRunner\"");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("buildTypes {");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("release {");
      _builder_1.newLine();
      _builder_1.append("\t            ");
      _builder_1.append("minifyEnabled false");
      _builder_1.newLine();
      _builder_1.append("\t            ");
      _builder_1.append("proguardFiles getDefaultProguardFile(\'proguard-android-optimize.txt\'), \'proguard-rules.pro\'");
      _builder_1.newLine();
      _builder_1.append("\t        ");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dependencies {");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("implementation fileTree(dir: \'libs\', include: [\'*.jar\'])");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("implementation \'androidx.appcompat:appcompat:1.0.2\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("implementation \'androidx.constraintlayout:constraintlayout:1.1.3\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("implementation \'androidx.legacy:legacy-support-v4:1.0.0\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("testImplementation \'junit:junit:4.12\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("androidTestImplementation \'androidx.test.ext:junit:1.1.0\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("androidTestImplementation \'androidx.test.espresso:espresso-core:3.1.1\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("implementation \'com.android.support:design:28.0.0\'");
      _builder_1.newLine();
      _builder_1.append("\t    ");
      _builder_1.append("implementation \'com.google.android.gms:play-services-maps:16.1.0\'");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      return _builder_1.toString();
    }
  }
}
