/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;
import org.xtext.example.mdsd.androidGenerator.Bundle;
import org.xtext.example.mdsd.androidGenerator.Fragment;
import org.xtext.example.mdsd.androidGenerator.Holder;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bundle</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.BundleImpl#getBundleRecipient <em>Bundle Recipient</em>}</li>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.BundleImpl#getHolder <em>Holder</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BundleImpl extends ButtonActionsImpl implements Bundle
{
  /**
   * The cached value of the '{@link #getBundleRecipient() <em>Bundle Recipient</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBundleRecipient()
   * @generated
   * @ordered
   */
  protected Fragment bundleRecipient;

  /**
   * The cached value of the '{@link #getHolder() <em>Holder</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHolder()
   * @generated
   * @ordered
   */
  protected Holder holder;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BundleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.BUNDLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fragment getBundleRecipient()
  {
    if (bundleRecipient != null && bundleRecipient.eIsProxy())
    {
      InternalEObject oldBundleRecipient = (InternalEObject)bundleRecipient;
      bundleRecipient = (Fragment)eResolveProxy(oldBundleRecipient);
      if (bundleRecipient != oldBundleRecipient)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT, oldBundleRecipient, bundleRecipient));
      }
    }
    return bundleRecipient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fragment basicGetBundleRecipient()
  {
    return bundleRecipient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBundleRecipient(Fragment newBundleRecipient)
  {
    Fragment oldBundleRecipient = bundleRecipient;
    bundleRecipient = newBundleRecipient;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT, oldBundleRecipient, bundleRecipient));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Holder getHolder()
  {
    return holder;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHolder(Holder newHolder, NotificationChain msgs)
  {
    Holder oldHolder = holder;
    holder = newHolder;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.BUNDLE__HOLDER, oldHolder, newHolder);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHolder(Holder newHolder)
  {
    if (newHolder != holder)
    {
      NotificationChain msgs = null;
      if (holder != null)
        msgs = ((InternalEObject)holder).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.BUNDLE__HOLDER, null, msgs);
      if (newHolder != null)
        msgs = ((InternalEObject)newHolder).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.BUNDLE__HOLDER, null, msgs);
      msgs = basicSetHolder(newHolder, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.BUNDLE__HOLDER, newHolder, newHolder));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__HOLDER:
        return basicSetHolder(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        if (resolve) return getBundleRecipient();
        return basicGetBundleRecipient();
      case AndroidGeneratorPackage.BUNDLE__HOLDER:
        return getHolder();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        setBundleRecipient((Fragment)newValue);
        return;
      case AndroidGeneratorPackage.BUNDLE__HOLDER:
        setHolder((Holder)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        setBundleRecipient((Fragment)null);
        return;
      case AndroidGeneratorPackage.BUNDLE__HOLDER:
        setHolder((Holder)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        return bundleRecipient != null;
      case AndroidGeneratorPackage.BUNDLE__HOLDER:
        return holder != null;
    }
    return super.eIsSet(featureID);
  }

} //BundleImpl
