/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;
import org.xtext.example.mdsd.androidGenerator.Bundle;
import org.xtext.example.mdsd.androidGenerator.Fragment;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bundle</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.BundleImpl#getBundleRecipient <em>Bundle Recipient</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BundleImpl extends ButtonActionsImpl implements Bundle
{
  /**
   * The cached value of the '{@link #getBundleRecipient() <em>Bundle Recipient</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBundleRecipient()
   * @generated
   * @ordered
   */
  protected Fragment bundleRecipient;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BundleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.BUNDLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fragment getBundleRecipient()
  {
    if (bundleRecipient != null && bundleRecipient.eIsProxy())
    {
      InternalEObject oldBundleRecipient = (InternalEObject)bundleRecipient;
      bundleRecipient = (Fragment)eResolveProxy(oldBundleRecipient);
      if (bundleRecipient != oldBundleRecipient)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT, oldBundleRecipient, bundleRecipient));
      }
    }
    return bundleRecipient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fragment basicGetBundleRecipient()
  {
    return bundleRecipient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBundleRecipient(Fragment newBundleRecipient)
  {
    Fragment oldBundleRecipient = bundleRecipient;
    bundleRecipient = newBundleRecipient;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT, oldBundleRecipient, bundleRecipient));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        if (resolve) return getBundleRecipient();
        return basicGetBundleRecipient();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        setBundleRecipient((Fragment)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        setBundleRecipient((Fragment)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.BUNDLE__BUNDLE_RECIPIENT:
        return bundleRecipient != null;
    }
    return super.eIsSet(featureID);
  }

} //BundleImpl
