/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;
import org.xtext.example.mdsd.androidGenerator.ButtonActions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Button Actions</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ButtonActionsImpl extends MinimalEObjectImpl.Container implements ButtonActions
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ButtonActionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.BUTTON_ACTIONS;
  }

} //ButtonActionsImpl
