/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;
import org.xtext.example.mdsd.androidGenerator.Meters;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Meters</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MetersImpl extends UnitImpl implements Meters
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.METERS;
  }

} //MetersImpl
