/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AndroidGeneratorStandaloneSetup extends AndroidGeneratorStandaloneSetupGenerated {

	def static void doSetup() {
		new AndroidGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
