/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.xtext.example.mdsd.scoping.AbstractAndroidGeneratorScopeProvider;

/**
 * This class contains custom scoping description.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AndroidGeneratorScopeProvider extends AbstractAndroidGeneratorScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from Button to Iterable<? extends EObject>"
      + "\nType mismatch: cannot convert from Fragment to Iterable<? extends EObject>");
  }
}
