/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mdsd.androidGenerator.Activity;
import org.xtext.example.mdsd.androidGenerator.ActivityLayoutAttributes;
import org.xtext.example.mdsd.androidGenerator.ActivityTypeAttributes;
import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Activity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityImpl#getActivityTypeAttributes <em>Activity Type Attributes</em>}</li>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityImpl#getActivityAttributes <em>Activity Attributes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActivityImpl extends ApplicationElementImpl implements Activity
{
  /**
   * The cached value of the '{@link #getActivityTypeAttributes() <em>Activity Type Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivityTypeAttributes()
   * @generated
   * @ordered
   */
  protected ActivityTypeAttributes activityTypeAttributes;

  /**
   * The cached value of the '{@link #getActivityAttributes() <em>Activity Attributes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivityAttributes()
   * @generated
   * @ordered
   */
  protected EList<ActivityLayoutAttributes> activityAttributes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActivityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.ACTIVITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActivityTypeAttributes getActivityTypeAttributes()
  {
    return activityTypeAttributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetActivityTypeAttributes(ActivityTypeAttributes newActivityTypeAttributes, NotificationChain msgs)
  {
    ActivityTypeAttributes oldActivityTypeAttributes = activityTypeAttributes;
    activityTypeAttributes = newActivityTypeAttributes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES, oldActivityTypeAttributes, newActivityTypeAttributes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setActivityTypeAttributes(ActivityTypeAttributes newActivityTypeAttributes)
  {
    if (newActivityTypeAttributes != activityTypeAttributes)
    {
      NotificationChain msgs = null;
      if (activityTypeAttributes != null)
        msgs = ((InternalEObject)activityTypeAttributes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES, null, msgs);
      if (newActivityTypeAttributes != null)
        msgs = ((InternalEObject)newActivityTypeAttributes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES, null, msgs);
      msgs = basicSetActivityTypeAttributes(newActivityTypeAttributes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES, newActivityTypeAttributes, newActivityTypeAttributes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ActivityLayoutAttributes> getActivityAttributes()
  {
    if (activityAttributes == null)
    {
      activityAttributes = new EObjectContainmentEList<ActivityLayoutAttributes>(ActivityLayoutAttributes.class, this, AndroidGeneratorPackage.ACTIVITY__ACTIVITY_ATTRIBUTES);
    }
    return activityAttributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES:
        return basicSetActivityTypeAttributes(null, msgs);
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_ATTRIBUTES:
        return ((InternalEList<?>)getActivityAttributes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES:
        return getActivityTypeAttributes();
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_ATTRIBUTES:
        return getActivityAttributes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES:
        setActivityTypeAttributes((ActivityTypeAttributes)newValue);
        return;
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_ATTRIBUTES:
        getActivityAttributes().clear();
        getActivityAttributes().addAll((Collection<? extends ActivityLayoutAttributes>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES:
        setActivityTypeAttributes((ActivityTypeAttributes)null);
        return;
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_ATTRIBUTES:
        getActivityAttributes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_TYPE_ATTRIBUTES:
        return activityTypeAttributes != null;
      case AndroidGeneratorPackage.ACTIVITY__ACTIVITY_ATTRIBUTES:
        return activityAttributes != null && !activityAttributes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ActivityImpl
