/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mdsd.androidGenerator.ActivityLayoutAttributes;
import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;
import org.xtext.example.mdsd.androidGenerator.LayoutElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Activity Layout Attributes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.ActivityLayoutAttributesImpl#getLayoutElements <em>Layout Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActivityLayoutAttributesImpl extends MinimalEObjectImpl.Container implements ActivityLayoutAttributes
{
  /**
   * The cached value of the '{@link #getLayoutElements() <em>Layout Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLayoutElements()
   * @generated
   * @ordered
   */
  protected EList<LayoutElement> layoutElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActivityLayoutAttributesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.ACTIVITY_LAYOUT_ATTRIBUTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LayoutElement> getLayoutElements()
  {
    if (layoutElements == null)
    {
      layoutElements = new EObjectContainmentEList<LayoutElement>(LayoutElement.class, this, AndroidGeneratorPackage.ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS);
    }
    return layoutElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS:
        return ((InternalEList<?>)getLayoutElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS:
        return getLayoutElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS:
        getLayoutElements().clear();
        getLayoutElements().addAll((Collection<? extends LayoutElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS:
        getLayoutElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.ACTIVITY_LAYOUT_ATTRIBUTES__LAYOUT_ELEMENTS:
        return layoutElements != null && !layoutElements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ActivityLayoutAttributesImpl
