/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.androidGenerator.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mdsd.androidGenerator.AndroidGeneratorPackage;
import org.xtext.example.mdsd.androidGenerator.MinSDK;
import org.xtext.example.mdsd.androidGenerator.TargetSDK;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Target SDK</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.TargetSDKImpl#getResult <em>Result</em>}</li>
 *   <li>{@link org.xtext.example.mdsd.androidGenerator.impl.TargetSDKImpl#getMinsdk <em>Minsdk</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TargetSDKImpl extends MinimalEObjectImpl.Container implements TargetSDK
{
  /**
   * The cached value of the '{@link #getResult() <em>Result</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResult()
   * @generated
   * @ordered
   */
  protected org.xtext.example.mdsd.androidGenerator.Number result;

  /**
   * The cached value of the '{@link #getMinsdk() <em>Minsdk</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinsdk()
   * @generated
   * @ordered
   */
  protected MinSDK minsdk;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TargetSDKImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidGeneratorPackage.Literals.TARGET_SDK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.example.mdsd.androidGenerator.Number getResult()
  {
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResult(org.xtext.example.mdsd.androidGenerator.Number newResult, NotificationChain msgs)
  {
    org.xtext.example.mdsd.androidGenerator.Number oldResult = result;
    result = newResult;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.TARGET_SDK__RESULT, oldResult, newResult);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResult(org.xtext.example.mdsd.androidGenerator.Number newResult)
  {
    if (newResult != result)
    {
      NotificationChain msgs = null;
      if (result != null)
        msgs = ((InternalEObject)result).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.TARGET_SDK__RESULT, null, msgs);
      if (newResult != null)
        msgs = ((InternalEObject)newResult).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.TARGET_SDK__RESULT, null, msgs);
      msgs = basicSetResult(newResult, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.TARGET_SDK__RESULT, newResult, newResult));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MinSDK getMinsdk()
  {
    return minsdk;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMinsdk(MinSDK newMinsdk, NotificationChain msgs)
  {
    MinSDK oldMinsdk = minsdk;
    minsdk = newMinsdk;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.TARGET_SDK__MINSDK, oldMinsdk, newMinsdk);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMinsdk(MinSDK newMinsdk)
  {
    if (newMinsdk != minsdk)
    {
      NotificationChain msgs = null;
      if (minsdk != null)
        msgs = ((InternalEObject)minsdk).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.TARGET_SDK__MINSDK, null, msgs);
      if (newMinsdk != null)
        msgs = ((InternalEObject)newMinsdk).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AndroidGeneratorPackage.TARGET_SDK__MINSDK, null, msgs);
      msgs = basicSetMinsdk(newMinsdk, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidGeneratorPackage.TARGET_SDK__MINSDK, newMinsdk, newMinsdk));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.TARGET_SDK__RESULT:
        return basicSetResult(null, msgs);
      case AndroidGeneratorPackage.TARGET_SDK__MINSDK:
        return basicSetMinsdk(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.TARGET_SDK__RESULT:
        return getResult();
      case AndroidGeneratorPackage.TARGET_SDK__MINSDK:
        return getMinsdk();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.TARGET_SDK__RESULT:
        setResult((org.xtext.example.mdsd.androidGenerator.Number)newValue);
        return;
      case AndroidGeneratorPackage.TARGET_SDK__MINSDK:
        setMinsdk((MinSDK)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.TARGET_SDK__RESULT:
        setResult((org.xtext.example.mdsd.androidGenerator.Number)null);
        return;
      case AndroidGeneratorPackage.TARGET_SDK__MINSDK:
        setMinsdk((MinSDK)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AndroidGeneratorPackage.TARGET_SDK__RESULT:
        return result != null;
      case AndroidGeneratorPackage.TARGET_SDK__MINSDK:
        return minsdk != null;
    }
    return super.eIsSet(featureID);
  }

} //TargetSDKImpl
