/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AndroidGeneratorUiModule extends AbstractAndroidGeneratorUiModule {

	public AndroidGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
